### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by g3ra456** [egg82/AdvancedEnchantments#25]
```
[20:51:05 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v4.19.25
java.lang.NoSuchMethodError: org.bukkit.Material.getHardness()F
        at me.egg82.ae.events.enchants.ExplosiveEvents.blockBreak(ExplosiveEvents.java:85) ~[?:?]
        at ninja.egg82.events.SingleEventSubscriber.call(SingleEventSubscriber.java:100) ~[?:?]
        at ninja.egg82.events.BukkitEventSubscriber.call(BukkitEventSubscriber.java:50) ~[?:?]
        at ninja.egg82.events.BukkitEventSubscriber.lambda$new$0(BukkitEventSubscriber.java:31) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:123) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:877) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by g3ra456** [comment]
[21:06:08 ERROR]: [AdvancedEnchantments] {m.e.a.e.e.BeheadingEvents} Could not load player data from Mojang (rate-limited?)
java.io.IOException: Could not load player data from Mojang (rate-limited?)
        at me.egg82.ae.services.lookup.BukkitPlayerInfo.uuidExpensive(BukkitPlayerInfo.java:146)
        at me.egg82.ae.services.lookup.BukkitPlayerInfo.<init>(BukkitPlayerInfo.java:56)
        at me.egg82.ae.services.lookup.PlayerLookup.get(PlayerLookup.java:32)
        at me.egg82.ae.events.enchants.BeheadingEvents.getPlayerSkull(BeheadingEvents.java:371)
        at me.egg82.ae.events.enchants.BeheadingEvents.death(BeheadingEvents.java:278)
        at ninja.egg82.events.SingleEventSubscriber.call(SingleEventSubscriber.java:100)
        at ninja.egg82.events.BukkitEventSubscriber.call(BukkitEventSubscriber.java:50)
        at ninja.egg82.events.BukkitEventSubscriber.lambda$new$0(BukkitEventSubscriber.java:31)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395)
        at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1116)
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956)
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005)
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1623)
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69)
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13)
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)

**Comment by g3ra456** [comment]
el primer error me da cuando uso Explosivo.
El segundo Error me sale cuando uso Encantamientos en la espada
