### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Altraze** [egg82/AdvancedEnchantments#6]
[Thu, 11. Jul 2019 18:21:24 UTC ERROR] {m.e.a.s.s.PaperSkinInfo} Failed to get skin data
[Thu, 11. Jul 2019 18:21:24 UTC ERROR] {m.e.a.e.e.e.e.EntityDeathBeheading} Could not get player skin.
java.io.IOException: Could not get player skin.
    at me.egg82.ae.services.skin.PaperSkinInfo.skinExpensive(PaperSkinInfo.java:172)
    at me.egg82.ae.services.skin.PaperSkinInfo.<init>(PaperSkinInfo.java:67)
    at me.egg82.ae.services.skin.SkinLookup.get(SkinLookup.java:26)
    at me.egg82.ae.events.enchants.entity.entityDeath.EntityDeathBeheading.getPlayerSkull(EntityDeathBeheading.java:221)
    at me.egg82.ae.events.enchants.entity.entityDeath.EntityDeathBeheading.getPlayerSkull(EntityDeathBeheading.java:211)
    at me.egg82.ae.events.enchants.entity.entityDeath.EntityDeathBeheading.accept(EntityDeathBeheading.java:146)
    at me.egg82.ae.AdvancedEnchantments.lambda$loadEvents$20(AdvancedEnchantments.java:239)
    at ninja.egg82.events.SingleEventSubscriber.call(SingleEventSubscriber.java:100)
    at ninja.egg82.events.BukkitEventSubscriber.call(BukkitEventSubscriber.java:50)
    at ninja.egg82.events.BukkitEventSubscriber.lambda$new$0(BukkitEventSubscriber.java:31)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
    at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:741)
    at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1416)
    at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354)
    at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198)
    at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(EntityMonster.java:56)
    at net.minecraft.server.v1_14_R1.EntityZombie.damageEntity(EntityZombie.java:280)
    at net.minecraft.server.v1_14_R1.EntityPigZombie.damageEntity(EntityPigZombie.java:138)
    at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1059)
    at net.minecraft.server.v114
R1.EntityPlayer.attack(EntityPlayer.java:1676)
    at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2062)
    at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51)
    at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6)
    at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
    at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
    at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002)
    at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995)
    at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91)
    at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978)
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912)
    at java.lang.Thread.run(Thread.java:748)

**Comment by Altraze** [comment]
also this one:
 INFO java.lang.IllegalArgumentException: bound must be positive
11.07 21:41:43 [Server] INFO at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_212]
11.07 21:41:43 [Server] INFO at me.egg82.ae.events.enchants.inventory.inventoryClick.InventoryClickGrindstoneRewrite.accept(InventoryClickGrindstoneRewrite.java:37) ~[?:?]
11.07 21:41:43 [Server] INFO at me.egg82.ae.AdvancedEnchantments.lambda$loadEvents$13(AdvancedEnchantments.java:235) ~[?:?]
11.07 21:41:43 [Server] INFO at ninja.egg82.events.SingleEventSubscriber.call(SingleEventSubscriber.java:100) ~[?:?]
11.07 21:41:43 [Server] INFO at ninja.egg82.events.BukkitEventSubscriber.call(BukkitEventSubscriber.java:50) ~[?:?]
11.07 21:41:43 [Server] INFO at ninja.egg82.events.BukkitEventSubscriber.lambda$new$0(BukkitEventSubscriber.java:31) ~[?:?]
11.07 21:41:43 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2341) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-127]
11.07 21:41:43 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-127]

**Comment by Altraze** [comment]
also antigravity doesnt work

**Comment by egg82** [comment]
Apologies for the delay, I've been repairing my main PC and it's both slightly more difficult to get work done on my laptop and also consuming a lot of time for the repairs.

The first error, "Failed to get skin data" - I would assume (and hope) it doesn't happen very often, or only when Mojang's skin servers are down. Some of the heads for the "beheading" enchant require player skins, so they're fetched using online sources that can sometimes (again, hopefully rarely) fail. Let me know if that happens more than once every blue moon.

the second error I can certainly look into, as that looks like a small error in my math for dropping experience in grindstones.

Finally, I tested antigravity fairly thoroughly and can confirm it does indeed work as intended. Every 60 ticks (about 3 seconds) the server runs a task that goes through each player's inventory and applies a powerful jump boost potion effect to them that will last 61 ticks. Because of this, it can take up to 3 seconds to apply the effect on a player when putting the boots on, and up to 3 seconds to remove the effect when taking the boots off.
