### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Altraze** [egg82/AdvancedEnchantments#9]
26.07 08:00:09 [Server] WARN [AdvancedEnchantments] Task #57 for AdvancedEnchantments v4.14.19 generated an exception
26.07 08:00:09 [Server] INFO java.util.ConcurrentModificationException: null
26.07 08:00:09 [Server] INFO at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[?:1.8.0_212]
26.07 08:00:09 [Server] INFO at java.util.TreeMap$KeyIterator.next(TreeMap.java:1265) ~[?:1.8.0_212]
26.07 08:00:09 [Server] INFO at net.jodah.expiringmap.ExpiringMap$EntryTreeHashMap$AbstractHashIterator.getNext(ExpiringMap.java:473) ~[?:?]
26.07 08:00:09 [Server] INFO at net.jodah.expiringmap.ExpiringMap$EntryTreeHashMap$EntryIterator.next(ExpiringMap.java:503) ~[?:?]
26.07 08:00:09 [Server] INFO at net.jodah.expiringmap.ExpiringMap$EntryTreeHashMap$EntryIterator.next(ExpiringMap.java:501) ~[?:?]
26.07 08:00:09 [Server] INFO at me.egg82.ae.tasks.TaskBleeding.run(TaskBleeding.java:16) ~[?:?]
26.07 08:00:09 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-146]
26.07 08:00:09 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-146]
26.07 08:00:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-146]
26.07 08:00:09 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-146]
26.07 08:00:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-146]
26.07 08:00:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-146]

**Comment by egg82** [comment]
Well, that's new.

https://github.com/jhalterman/expiringmap
https://i.imgur.com/DI6T718.png

Maybe related to https://github.com/jhalterman/expiringmap/issues/30 ?

**Comment by egg82** [comment]
It looks like attempting to modify the map while iterating it throws the exception, which definitely breaks the contract of a ConcurrentMap. That's good.

**Comment by Altraze** [comment]
so how do i fix that?

**Comment by egg82** [comment]
It's on my end, so I'll need to fix it somehow. Will be in an update soon.

**Comment by Altraze** [comment]
ok thanks

**Comment by Altraze** [comment]
i am also getting these messages again : [Sun, 28. Jul 2019 08:01:59 UTC ERROR] Could not pass event PlayerAnimationEvent to AdvancedEnchantments v4.14.19

**Comment by egg82** [comment]
What's the full error look like? All that tells me is that there was an error in an event I was handling. I need to know where and why, exactly. The rest of the error tells me that information.

**Comment by Altraze** [comment]
[08:10:19] [Server thread/ERROR]: Could not pass event PlayerAnimationEvent to AdvancedEnchantments v4.14.19
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
	at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
	at me.egg82.ae.hooks.ProtocolLibHook.sendMulti(ProtocolLibHook.java:190) ~[?:?]
	at me.egg82.ae.hooks.ProtocolLibHook.sendFake(ProtocolLibHook.java:126) ~[?:?]
	at me.egg82.ae.events.enchants.MirageEvents.raise(MirageEvents.java:121) ~[?:?]
	at me.egg82.ae.events.enchants.MirageEvents.swing(MirageEvents.java:77) ~[?:?]
	at ninja.egg82.events.SingleEventSubscriber.call(SingleEventSubscriber.java:100) ~[?:?]
	at ninja.egg82.events.BukkitEventSubscriber.call(BukkitEventSubscriber.java:50) ~[?:?]
	at ninja.egg82.events.BukkitEventSubscriber.lambda$new$0(BukkitEventSubscriber.java:31) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-152]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-152]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1843) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.PacketPlayInArmAnimation.a(SourceFile:32) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.PacketPlayInArmAnimation.a(SourceFile:9) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-152]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by egg82** [comment]
Do you have the correct version of ProtocolLib installed?

**Comment by egg82** [comment]
Looks related to this thread:
https://www.spigotmc.org/threads/protocollib.36230/page-54

Seems unlikely it's an issue with AE. Re-open if that is  not the case.
